name: "Development - Plan and Deploy"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: mms-d-prj-marcusmdesouza
  WORKLOAD_IDENTITY_PROVIDER: projects/291916272632/locations/global/workloadIdentityPools/github/providers/github-repo

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: "${{ env.WORKLOAD_IDENTITY_PROVIDER }}"
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform init
        run: terraform init
        working-directory: infra/terraform/environments/development
      - name: Terraform plan
        run: terraform plan -out=tfplan -lock-timeout=60m
        working-directory: infra/terraform/environments/development
        env:
          TF_VAR_project_id: ${{ env.PROJECT_ID }}
      - name: Upload Terraform plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: infra/terraform/environments/development/tfplan

  deploy:
    needs: plan
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: "${{ env.WORKLOAD_IDENTITY_PROVIDER }}"
      - uses: hashicorp/setup-terraform@v3
      - name: Download Terraform plan artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: infra/terraform/environments/development
      - name: Terraform init
        run: terraform init
        working-directory: infra/terraform/environments/development
      - name: Terraform apply
        run: terraform apply --auto-approve -lock-timeout=60m tfplan
        working-directory: infra/terraform/environments/development
        env:
          TF_VAR_project_id: ${{ env.PROJECT_ID }}
